# Changes here will be overwritten by Copier
_commit: 0.1.0
_src_path: gh:ansible-selfhosted/selfhosted-role-template
author_company: ''
author_email: git@speakintel.net
author_name: SpeakinTelnet
collection_name: services
copyright_holder: SpeakinTelnet
license: MIT
related_url: https://www.bookstackapp.com/docs/
repository_host: github.com
repository_url: https://github.com/ansible-selfhosted/selfhosted.services.bookstack
role_name: bookstack
short_description: A role to deploy Bookstack using rootless Podman with systemd.
