---
role_name_check: 1
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/speakintelnet/pinp-molecule:latest
    privileged: true
    pre_build_image: true
    systemd: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_user: podman
        bookstack_app_key: base64:BonYAfY/+yn60fTWjnVdVPOFjYdF/psJ+snw6e1GkbI=
verifier:
  name: ansible
