---
- name: Verify web server
  hosts: all
  tasks:
    - name: Wait for the web server to start
      ansible.builtin.wait_for:
        host: http://127.0.0.1:8080/status
        delay: 10
        timeout: 60

    - name: Verify that the web server is serving content
      ansible.builtin.uri:
        url: http://127.0.0.1:8080/status
        return_content: true
      register: web_content

    - name: Check if the web server is up
      ansible.builtin.assert:
        that:
          - "'{\"database\":true,\"cache\":true,\"session\":true}' in web_content.content"
